# Write your MySQL query statement below
SELECT
    B.PRODUCT_ID,
    ROUND(SUM(A.PRICE * B.UNITS) / SUM(B.UNITS), 2) AS AVERAGE_PRICE
FROM
    PRICES A
JOIN UNITSSOLD B ON A.PRODUCT_ID = B.PRODUCT_ID
AND B.PURCHASE_DATE BETWEEN A.START_DATE AND A.END_DATE
GROUP BY B.PRODUCT_ID