SELECT
    CONTEST_ID,
    ROUND(COUNT(DISTINCT(USER_ID)) * 100 / TOTAL, 2) AS PERCENTAGE
FROM
    REGISTER A,
    (SELECT 
        COUNT(DISTINCT(USER_ID)) AS TOTAL 
    FROM
        USERS
    ) COUNT_USERS
GROUP BY CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID ASC