SELECT
    ROUND(
        COUNT(DISTINCT PLAYER_ID) / (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY), 2) AS FRACTION
FROM
    ACTIVITY
WHERE
    (PLAYER_ID, DATE_SUB(EVENT_DATE, INTERVAL 1 DAY)) IN (
        SELECT
            PLAYER_ID,
            MIN(EVENT_DATE) AS FIRST_LOGIN
        FROM
            ACTIVITY
        GROUP BY
            PLAYER_ID
    )