SELECT
    A.PRODUCT_NAME,
    SUM (B.UNIT) AS UNIT
FROM
    PRODUCTS A
    INNER JOIN ORDERS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE
    MONTH(ORDER_DATE) = 02
GROUP BY
    A.PRODUCT_NAME
HAVING
    UNIT >= 100